version: "3"

services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8888:8000"
    container_name: selenium
    # volumes:
    #   - ./app:/app
#    networks:
#      - network

#   nginx:
#     image: 'nginx:1.23.3-alpine'
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
#     depends_on:
#       - selenium
#     restart: unless-stopped
#     ports:
#       - 8888:80
#     container_name: nginx
#     networks:
#       - network

# networks:
#   network:
#     driver: bridge